spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: De^ga^ja12
    url: jdbc:mysql://dev.db.proteen.degaja.com/proteen
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
jwt:
  secret:
    access-key: test
    refresh-key: test