spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: De^ga^ja12
    url: jdbc:mysql://dev.db.proteen.degaja.com/proteen
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
jwt:
  secret:
    access-key: test
    refresh-key: test

cloud:
  aws:
    s3:
      bucket: proteen-repository
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIASZJGQIF762DXVGPR
      secretKey: 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